// resources/js/views/Home.vue
<script>
import HomeHero from '../components/Home/HomeHero';
import HomeInformation from '../components/Home/HomeInformation';
import HomeFoodCategories from '../components/Home/HomeFoodCategories';
export default {
  components: {
    HomeHero,
    HomeInformation,
    HomeFoodCategories,
  },
};
</script>

<template>
  <div>
    <HomeHero />
    <HomeInformation />
    <HomeFoodCategories />
  </div>
</template>

// web/src/views/Home.tsx
import React from 'react'
import { AboutSection } from '../components/Home/AboutSection/AboutSection'
import { FoodPreviewSection } from '../components/Home/FoodPreviewSection/FoodPreviewSection'
import { Hero } from '../components/Home/Hero/Hero'

export const Home = () => {
  return (
    <>
      <Hero />
      <AboutSection />
      <FoodPreviewSection />
    </>
  )
}
