// web/src/components/Navigation/Navigation.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import LogoImage from '../../assets/img/resized-logo.png'
import { Links, Logo, NavContainer, NavWrapper } from './Navigation.styles'

export const Navigation = () => {
  return (
    <NavContainer>
      <NavWrapper>
        <Logo to="/">
          <img src={LogoImage} alt="Logo" />
        </Logo>
        <div>
          <Links>
            <li>
              <Link to="/menu">Food</Link>
            </li>
            <li>
              <Link to="/about">About Us</Link>
            </li>
            <li>
              <Link to="/offers">Offers</Link>
            </li>
            <li>
              <Link to="/contact">Contact</Link>
            </li>
            <li>
              <Link to="/menu">Order</Link>
            </li>
          </Links>
        </div>
      </NavWrapper>
    </NavContainer>
  )
}

// resources/js/components/Navigation.vue
<template>
  <div class="nav-container">
    <nav>
      <a href="/" class="logo">
        <img src="/img/resized.png" />
      </a>
      <div class="menu">
        <ul class="links">
          <li>
            <router-link to="/menu">
              Food
            </router-link>
          </li>
          <li>
            <router-link to="/about">
              About Us
            </router-link>
          </li>
          <li>
            <router-link to="/offers">
              Offers
            </router-link>
          </li>
          <li>
            <router-link to="/contact">
              Contact
            </router-link>
          </li>
          <li>
            <router-link to="/menu">
              Order
            </router-link>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</template>

<style lang="scss">
@import '../../sass/_variables.scss';
@import '../../sass/_navigation.scss';
</style>
